# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-8RVOI32jEonBexVhjD44cCK8CgUOAK
"""

from fastapi import FastAPI, Request
from app.mailgen import MailGenerator
from app.corrector import KoreanTextCorrector

app = FastAPI()

# 모델/파일 경로 (필요에 따라 파일명 수정)
EMBED_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
GEN_MODEL = "42dot/42dot_LLM-SFT-1.3B"
EMBED_FILE = "app/email_embeddings.npy"
TEXT_FILE = "app/email_texts.npy"
INDEX_FILE = "app/email_index.faiss"

mailgen = MailGenerator(
    embed_model=EMBED_MODEL,
    gen_model=GEN_MODEL,
    embed_file=EMBED_FILE,
    text_file=TEXT_FILE,
    index_file=INDEX_FILE
)
corrector = KoreanTextCorrector()

@app.post("/ai/mail")
async def generate_mail(req: Request):
    data = await req.json()
    text = data["text"]
    email_text = mailgen.make_email(text)
    corrected_email = corrector.correct_text(email_text)
    return {"result": corrected_email}

@app.post("/ai/correct")
async def grammar_correct(req: Request):
    data = await req.json()
    text = data["text"]
    corrected = corrector.correct_text(text)
    return {"result": corrected}