# -*- coding: utf-8 -*-
"""mailgen_ec2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5Bcvs0Z8V6OUy-LPd00uPNVaDQpEohy
"""

import numpy as np
import faiss
import torch
from sklearn.preprocessing import normalize
from transformers import AutoTokenizer, AutoModel, AutoModelForCausalLM
from konlpy.tag import Okt
from sentence_transformers import SentenceTransformer
import re

class MailGenerator:
    def __init__(self,
                 embed_model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
                 gen_model_name="42dot/42dot_LLM-SFT-1.3B",
                 embed_file="app/email_embeddings.npy",
                 text_file="app/email_texts.npy",
                 index_file="app/email_index.faiss"):
        self.embed_tokenizer = AutoTokenizer.from_pretrained(embed_model_name)
        self.embed_model = AutoModel.from_pretrained(embed_model_name)
        self.gen_tokenizer = AutoTokenizer.from_pretrained(gen_model_name)
        self.gen_model = AutoModelForCausalLM.from_pretrained(gen_model_name)
        self.st_model = SentenceTransformer(embed_model_name)
        self.okt = Okt()

        self.embed_file = embed_file
        self.text_file = text_file
        self.index_file = index_file

    def get_embedding(self, text):
        inputs = self.embed_tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=512)
        with torch.no_grad():
            output = self.embed_model(**inputs).last_hidden_state.mean(dim=1)
        return output.squeeze().numpy().astype("float32")

    def extract_keywords(self, text):
        return [word for word, pos in self.okt.pos(text) if pos in ["Noun", "Verb", "Adjective"]]

    def search_similar_emails(self, user_request, top_k=5, keyword_boost=0.05):
        embeddings = np.load(self.embed_file)
        email_texts = np.load(self.text_file, allow_pickle=True)
        index = faiss.read_index(self.index_file)

        user_emb = self.get_embedding(user_request).reshape(1, -1)
        user_emb = normalize(user_emb, axis=1)
        keywords = self.extract_keywords(user_request)

        D, I = index.search(user_emb.astype("float32"), len(email_texts))

        results = []
        for i, idx in enumerate(I[0]):
            email = email_texts[idx]
            sim_score = float(D[0][i])
            keyword_count = sum(kw in email for kw in keywords)
            final_score = sim_score + keyword_boost * keyword_count
            results.append((email, final_score))

        results.sort(key=lambda x: x[1], reverse=True)
        return results[:top_k]

    def generate_email_from_context(self, user_request, context_emails,
                                    max_length=2048, max_new_tokens=150, min_new_tokens=50, max_email_token_length=500):
        context_list = []
        total_token_count = 0
        prompt_suffix = f"\n\n[요청] {user_request}\n[완성된 이메일]\n"
        suffix_tokens = self.gen_tokenizer.encode(prompt_suffix, add_special_tokens=False)
        available_budget = max_length - max_new_tokens - len(suffix_tokens)

        for email_text, _ in context_emails:
            email_tokens = self.gen_tokenizer.encode(email_text, add_special_tokens=False)
            sep_tokens = self.gen_tokenizer.encode("\n---\n", add_special_tokens=False)
            sep_len = len(sep_tokens)
            if len(email_tokens) > max_email_token_length:
                continue
            extra_tokens = sep_len if context_list else 0
            if total_token_count + len(email_tokens) + extra_tokens <= available_budget:
                context_list.append(email_text)
                total_token_count += len(email_tokens) + extra_tokens

        context = "\n---\n".join(context_list)
        prompt = f"{context}{prompt_suffix}"

        input_ids = self.gen_tokenizer.encode(prompt, return_tensors="pt")
        attention_mask = torch.ones_like(input_ids)

        output = self.gen_model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=max_new_tokens,
            min_new_tokens=min_new_tokens,
            early_stopping=True,
            do_sample=True,
            temperature=0.6,
            top_k=30,
            top_p=0.90,
            pad_token_id=self.gen_tokenizer.eos_token_id
        )

        decoded = self.gen_tokenizer.decode(output[0], skip_special_tokens=True)
        return decoded.split("[완성된 이메일]")[-1].strip()

    def is_complete_sentence(self, sentence):
        sentence = sentence.strip()
        if not sentence:
            return False
        if sentence[-1] in ".?!":
            return True
        if re.search(r"(올림|드림)$", sentence):
            return True
        m = re.match(r"^(\d+\.\s*|[•\-–]\s*)", sentence)
        if m:
            if len(sentence) <= 7 or re.search(r"([가-힣])$", sentence):
                return False
            if re.search(r"(다|요|니다|습니다|줍니다|바랍니다|[.?!:])$", sentence):
                return True
            return False
        return False

    def remove_similar_sentences(self, email, threshold=0.93):
        email = "\n".join([l for l in email.split('\n') if not l.strip().startswith(("[요청]", "[답변]", "[완성된 이메일]"))])
        paragraphs = re.split(r"\n\s*\n", email)
        clean_paragraphs = []
        seen_paragraphs = set()

        for para in paragraphs:
            lines = [l for l in para.split('\n') if l.strip()]
            if not lines:
                continue

            seen = set()
            unique_lines = []
            for l in lines:
                l_clean = l.strip().rstrip('.').rstrip()
                if l_clean and l_clean not in seen:
                    unique_lines.append(l)
                    seen.add(l_clean)

            if len(unique_lines) == 1:
                filtered_lines = unique_lines
            else:
                embeddings = self.st_model.encode(unique_lines)
                keep = [0]
                for i in range(1, len(unique_lines)):
                    sims = [np.dot(embeddings[i], embeddings[j]) / (np.linalg.norm(embeddings[i]) * np.linalg.norm(embeddings[j])) for j in keep]
                    if max(sims) < threshold:
                        keep.append(i)
                filtered_lines = [unique_lines[i] for i in keep]

            if filtered_lines:
                para_text = '\n'.join(filtered_lines)
                if para_text not in seen_paragraphs:
                    clean_paragraphs.append(para_text)
                    seen_paragraphs.add(para_text)

        full_mail = '\n\n'.join(clean_paragraphs)
        lines = full_mail.split('\n')
        if lines and not self.is_complete_sentence(lines[-1]):
            lines.pop()
        return '\n'.join(lines).lstrip('- \n')

    def generate(self, user_request):
        top_emails = self.search_similar_emails(user_request)
        raw_email = self.generate_email_from_context(user_request, top_emails)
        clean_email = self.remove_similar_sentences(raw_email)
        return clean_email