# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-8RVOI32jEonBexVhjD44cCK8CgUOAK
"""
from fastapi import FastAPI, Request, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from app.mailgen import MailGenerator
from app.corrector import KoreanTextCorrector
    
app = FastAPI()

#CORS 설정
origins = [
    "http://43.200.121.238",  # 다른 EC2 인스턴스의 공인 IP
    "http://localhost",       # 로컬 개발 환경 (옵션)
    "http://127.0.0.1",
]

# CORS 미들웨어 추가
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,  # 허용할 출처 (도메인)
    allow_credentials=True,
    allow_methods=["*"],    # 모든 HTTP 메서드 허용
    allow_headers=["*"],    # 모든 헤더 허용
)

# 모델/파일 경로 (필요에 따라 파일명 수정)
EMBED_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
GEN_MODEL = "42dot/42dot_LLM-SFT-1.3B"
EMBED_FILE = "src/email_embeddings.npy"
TEXT_FILE = "src/email_texts.npy"
INDEX_FILE = "src/email_index.faiss"

mailgen = MailGenerator(
    embed_model_name=EMBED_MODEL,
    gen_model_name=GEN_MODEL,
    embed_file=EMBED_FILE,
    text_file=TEXT_FILE,
    index_file=INDEX_FILE
)
corrector = KoreanTextCorrector()

class AIRequest(BaseModel):
    customContent: str = None
    content: str = None
    prompt: str = None

@app.post("/templates/ai-made")
async def generate_refined_content(req: Request):
    try:
        data = await req.json() 
        custom_content = data.get("customContent")

        if not custom_content:  # 빈 값 처리
            raise HTTPException(status_code=400, detail="Custom content cannot be empty.")
        
        corrected_email = corrector.correct_text(custom_content)
        return {"refinedContent": corrected_email}
    
    except KeyError:
        raise HTTPException(status_code=400, detail="Missing required field: 'customContent'")
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid input data: {str(e)}")

@app.post("/ai/refine")
async def refine_content(req: Request):
    try: 
        data = await req.json()  
        content = data.get("content")  

        if not content:  # 빈 값 처리
            raise HTTPException(status_code=400, detail="Content cannot be empty.")
        
        corrected_content = corrector.correct_text(content)
        return {"refined": corrected_content}
    
    except KeyError:
        raise HTTPException(status_code=400, detail="Missing required field: 'content'")
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid input data: {str(e)}")

@app.post("/ai/generate")
async def generate_email(req: Request):
    try: 
        data = await req.json()
        prompt = data.get("prompt")

        if not prompt:  # 빈 값 처리
            raise HTTPException(status_code=400, detail="Prompt cannot be empty.")
        
        email_text = mailgen.generate(prompt)
        #corrected_email = corrector.correct_text(email_text)
        return {"content": email_text}
    
    except KeyError:
        raise HTTPException(status_code=400, detail="Missing required field: 'prompt'")
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid input data: {str(e)}")    